{% set name = "cytosnake" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../


build:
  # setting platform independent
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - python
  build:
    - python
    - pip
    - setuptools
  run:
    - python=3.10.*
    - pip
    - conda-forge::numpy>=1.17
    - conda-forge::mamba>=1.5.0
    - conda-forge::myst-parser>=2.0.0
    - conda-forge::pre-commit>=3.3.0
    - conda-forge::pyyaml>=6.0.0
    - conda-forge::furo=2023.7.26
    - bioconda::snakemake>=7.32

channels:
  - conda-forge
  - bioconda
  - defaults

test:
  import:
    - cytosnake

about:
  home: https://github.com/WayScience/CytoSnake
  license: CC By 4.0
  license_file: LICENSE.md
  summary: Orchestrating high-dimensional cell morphology data processing pipelines
  version: 0.0.1
  build: 1
  maintainers:
    - name: Erik Serrano
      email: erik.serrano@cuanschutz.edut
  doc_url: https://cytosnake.readthedocs.io/
  tags:
    - workflow
    - pipeline
    - cell-morphology
    - microscopy-images
  requires:
    - python >=3.10
