{% set name = "cytosnake" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/WayScience/CytoSnake/archive/v{{ version }}.tar.gz"
  sha256: 39cc1d5284380492c7a1a41c7a84ee6269c0c2c57ec559a1c8af8a4a95b8f26b


build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python
  ignore_prefix_files:
    - docs
    - tests
  run_exports:
     - {{ pin_subpackage('cytosnake', max_pin="x.x") }}

requirements:
  build:
    - python >=3.6, <=3.10
    - pip
    - setuptools
  host:
    - python >=3.6, <=3.10
  run:
    - python =3.10.*
    - pip
    - mamba
    - numpy >=1.20
    - pyyaml >=6.0.0
    - snakemake >=7.24

test:
   imports:
     - cytosnake
   commands:
     - pip check
   requires:
     - pip

about:
  home: https://github.com/WayScience/CytoSnake
  license: CC-BY-4.0
  license_file: LICENSE.md
  summary: Orchestrating high-dimensional cell morphology data processing pipelines
  doc_url: https://cytosnake.readthedocs.io/
  tags:
    - workflow
    - pipeline
    - cell-morphology
    - microscopy-images

extra:
   recipe-maintainers:
     - axiomcura
     - gwaybio
