package:
  name: cytosnake
  version: 0.0.1

source:
  path: .

build:
  # setting platform independent
  noarch: python

requirements:
  build:
    - python
  run:
    - python=3.10.*
    - pip
    - numpy>=1.17
    - conda-forge::mamba>=1.5.0
    - conda-forge::myst-parser>=2.0.0
    - conda-forge::pre-commit>=3.3.0
    - conda-forge::pyyaml>=6.0.0
    - bioconda::snakemake>=7.32
  pip:
    - rst-to-myst
    - furo==2023.7.26

channels:
  - conda-forge
  - bioconda
  - defaults

about:
  home: https://github.com/WayScience/CytoSnake
  license: CC By 4.0
  license_file: LICENSE.md
  summary: Orchestrating high-dimensional cell morphology data processing pipelines
  version: 0.0.1
  build: 1
  maintainers:
    - name: Erik Serrano
      email: erik.serrano@cuanschutz.edut
  doc_url: https://cytosnake.readthedocs.io/
  tags:
    - workflow
    - pipeline
    - cell-morphology
    - microscopy-images
  requires:
    - python >=3.10
