name: cp_process_singlecells_configs

# Documentation
docs: |
  Description:
  ------------
  Converts sqlite plate data into parquet and returns selected features in csv
  format

  Workflow Steps:
  ---------------
  Below the workflow steps are separated in chunks.

  cytotable_convert:
    Takes in sqlite file and converts it into a parquet file.

    Uses CytoTable's convert workflow which can be found in:
    https://cytomining.github.io/CytoTable/python-api.html#cytotable.convert.convert

  annoate_configs:
    Takes in single-cell morphology profiles an annoates them with given metadata

    Uses Pycytominer's annoatation module:
    https://github.com/cytomining/pycytominer/blob/master/pycytominer/annotate.py

  normalize_configs:
    Noramlizes single cell morphological features

    Uses Pycytominer normalization module:
    https://github.com/cytomining/pycytominer/blob/master/pycytominer/normalize.py


  feature_select_configs:
    Selects morphological features from normalized dataset

    Uses Pycytominer feature extraction module
    https://github.com/cytomining/pycytominer/blob/master/pycytominer/feature_select.py


cytotable_convert:
  params:
    input_data: plate_data
    dest_datatype: parquet
    source_datatype: sqlite
    concat: True
    join: True
    infer_common_schema: True
    drop_null: True
    preset: cellprofiler_sqlite
    log_level: ERROR

annotate_configs:
  params:
    input_data: plate_data
    join_on:
      - Metadata_well_position
      - Image_Metadata_Well
    add_metadata_id_to_platemap: True
    format_broad_cmap: False
    clean_cellprofiler: True
    external_metadata: null
    external_join_left: null
    external_join_right: null
    compression_options:
      method: "gzip"
      mtime: 1
    float_format: null
    cmap_args: {}

normalize_configs:
  params:
    input_data: plate_data
    features: infer
    image_features: False
    meta_features: infer
    samples: all
    method: mad_robustize
    compression_options:
      method: gzip
      mtime: 1
    float_format: null
    mad_robustize_epsilon: 1.0e-18
    spherize_center: True
    spherize_method: ZCA-cor
    spherize_epsilon: 1.0e-6

feature_select_configs:
  params:
    input_data: normalized
    features: infer
    image_features: False
    samples: all
    operation:
      - variance_threshold
      - drop_na_columns
      - correlation_threshold
      - drop_outliers
      - blocklist
    na_cutoff: 0.05
    corr_threshold: 0.9
    corr_method: pearson
    freq_cut: 0.05
    unique_cut: 0.1
    compression_options:
      method: gzip
      mtime: 1
    float_format: null
    blocklist_file: null
    outlier_cutoff: 15
    noise_removal_perturb_groups: null
    noise_removal_stdev_cutoff: null
