name: cp_process

# Documentation
docs: |
  Description:
  ------------
  Traditional workflow

  Workflow Steps:
  ---------------
  Below the workflow steps are separated in chunks.

  single_cell_config:
    Parameters used for SingleCell object, used for interacting with single cell data.
    For more documenation about SingelCell please refer to here:

  aggregate_configs:
    aggregates single-cell morphology at a given level of aggregation. For example
    one can aggregate single cell at the well level. This means that all cells within
    a well will be aggregated into a single data point containing all morphology features.

  annotate_configs:
    Adds meta data to the given dataset. This includes information regarding to well
    position, types of perturbations, etc.

  normalize_configs:
    Applies normalization to given dataset

  feature_select_configs:
    Select features from given dataset

  consensus_configs:
    Creates a consensus profile. Consensus profiles are unique signatures that are mapped
    to a given perturbations.

single_cell_configs:
  params:
    strata:
      - Image_Metadata_Plate
      - Image_Metadata_Well
    image_cols:
      - TableNumber
      - ImageNumber
      - Image_Metadata_Site
    aggregation_operation: median
    compartments:
      - cells
      - cytoplasm
      - nuclei
    compartment_linking_cols: default_linking_cols
    merge_cols:
      - TableNumber
      - ImageNumber
    add_image_features: False
    image_feature_categories: None
    features: infer
    load_image_data: True
    subsample_frac: 1
    subsample_n: all
    subsampling_random_state: none
    fields_of_view: all
    fields_of_view_feature: Metadata_Site
    object_feature: Metadata_ObjectNumber

aggregate_configs:
  params:
    input_data: plate_data
    compute_subsample: False
    output_file: null
    compression_options: gzip
    float_format: null
    n_aggregation_memory_strata: 1

annotate_configs:
  params:
    input_data: aggregated
    join_on:
      - Metadata_well_position
      - Image_Metadata_Well
    add_metadata_id_to_platemap: True
    format_broad_cmap: False
    clean_cellprofiler: True
    external_metadata: "none"
    external_join_left: "none"
    external_join_right: "none"
    compression_options:
      method: "gzip"
      mtime: 1
    float_format: null
    cmap_args: {}


normalize_configs:
  params:
    input_data: annotated
    features: infer
    image_features: False
    meta_features: infer
    samples: all
    method: mad_robustize
    compression_options:
      method: gzip
      mtime: 1
    float_format: null
    mad_robustize_epsilon: 1.0e-18
    spherize_center: True
    spherize_method: ZCA-cor
    spherize_epsilon: 1.0e-6

feature_select_configs:
  params:
    input_data: normalized
    features: infer
    image_features: False
    samples: all
    operation:
      - variance_threshold
      - drop_na_columns
      - correlation_threshold
      - drop_outliers
      - blocklist
    na_cutoff: 0.05
    corr_threshold: 0.9
    corr_method: pearson
    freq_cut: 0.05
    unique_cut: 0.1
    compression_options:
      method: gzip
      mtime: 1
    float_format: null
    blocklist_file: null
    outlier_cutoff: 15
    noise_removal_perturb_groups: null
    noise_removal_stdev_cutoff: null

consensus_config:
  params:
    input_data: feature_select
    replicate_columns:
      - Metadata_cell_line
      - Metadata_pert_name
    operation: median
    features: infer
    compression_options: null
    float_format: null
    modz_args: { "method": "spearman" }
