config_name: cytopipe_defaults
analysis_configs:
  preprocessing:
    threads: 4
config_paths:
  single_cell: "configs/analysis_configs/single_cell_configs.yaml"
  annotate: "configs/analysis_configs/annotate_configs.yaml"
  normalize: "configs/analysis_configs/normalize_configs.yaml"
  feature_select: "configs/analysis_configs/feature_select_configs.yaml"
  aggregate: "configs/analysis_configs/aggregate_configs.yaml"
  consensus_config: "configs/analysis_configs/consensus_configs.yaml"
  dp_data: "configs/analysis_configs/dp_data_configs.yaml"
  dp_aggregator: "configs/analysis_configs/dp_aggregator_config.yaml"
  dp_normalization: "configs/analysis_configs/dp_normalization_config.yaml"
workflows:
  cp_process: "./Snakefile"
  dp_process: "./dp_process.smk"
