aggregate_configs:
  params:
  strata:
    - Metadata_Plate
    - Metadata_Well
  features: infer
  operation: median
  output_file: none
  compute_object_count: False
  object_feature: Metadata_ObjectNumber
  subset_data_df: none
  compression_options:
    method: gzip
    mtime: 1
  float_format: null
