annotate_configs:
  params:
    join_on:
      - Metadata_well_position
      - Image_Metadata_Well
    add_metadata_id_to_platemap: True
    format_broad_cmap: False
    clean_cellprofiler: True
    external_metadata: null
    external_join_left: null
    external_join_right: null
    compression_options:
      method: "gzip"
      mtime: 1
    float_format: null
    cmap_args: {}
